[phases.setup]
nixPkgs = ["jdk", "maven"]

[phases.install]
cmds = []

[phases.build]
cmds = ["cd springboot && mvn clean package -DskipTests"]

[start]
cmd = "java -jar springboot/target/smartcity-api-1.0.0.jar"
